# Generated by Django 5.1.2 on 2024-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato_numero', models.CharField(max_length=20)),
                ('frequencia_de_entrega', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
