# Generated by Django 5.1.2 on 2024-11-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='material',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
