# Generated by Django 5.1.2 on 2024-11-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depoimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depoimento',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='depoimento',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
