# Generated by Django 5.1.2 on 2024-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=10, max_digits=15)),
                ('imagem', models.ImageField(upload_to='brinquedos/img/')),
            ],
        ),
    ]
