# Generated by Django 5.1.2 on 2024-10-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brinquedos', '0002_rename_doacao_brinquedo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brinquedo',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='brinquedos.brinquedo')),
            ],
        ),
    ]
